version: '3'
services:
  database:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgsql
  back:
    build: ./back
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./back:/back
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgsql
      - DATABASE_URL=postgres://database
      
volumes:
  db_data:
