default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  url:  <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: nuuvem_dev

test:
  <<: *default
  database: nuuvem_test

production:
  <<: *default
  database: nuuvem
  username: back
  password: <%= ENV['BACK_DATABASE_PASSWORD'] %>
